#!/usr/bin/env python

import rospy, sys, os, time
import string
import warnings

from gazebo_ros import gazebo_interface
from std_srvs.srv import Empty
from std_msgs.msg import Float64

def unpause(gazebo_namespace):
	rospy.loginfo("Waiting for service %s/unpause_physics"%gazebo_namespace)
	rospy.wait_for_service(gazebo_namespace+'/unpause_physics')
	rospy.loginfo("temporary hack to **fix** the -J joint position option (issue #93), sleeping for 1 second to avoid race condition.");
	time.sleep(1)
	try:
		unpause_physics = rospy.ServiceProxy(gazebo_namespace+'/unpause_physics', Empty)
		rospy.loginfo("Calling service %s/unpause_physics"%gazebo_namespace)
		resp = unpause_physics()
		return
	except rospy.ServiceException, e:
		print "Service call failed: %s"%e


if __name__ == "__main__":
	if len(sys.argv) < 2:
		sleep_time = 0.0
	else:
		print sys.argv[1]
		sleep_time = float(sys.argv[1])

	# Defined the variables
	param_name              = ""
	model_name              = ""
	robot_namespace         = ""
	gazebo_namespace        = "/gazebo"
	joint_names             = []
	joint_positions         = []

	# Setting the parameters
	model_name = 'hyq'
	param_name = 'robot_description'
	# LF foot
	joint_names.append('lf_haa_joint')
	joint_positions.append(-0.2)
	joint_names.append('lf_hfe_joint')
	joint_positions.append(0.75)
	joint_names.append('lf_kfe_joint')
	joint_positions.append(-1.5)
	# RF foot
	joint_names.append('rf_haa_joint')
	joint_positions.append(-0.2)
	joint_names.append('rf_hfe_joint')
	joint_positions.append(0.75)
	joint_names.append('rf_kfe_joint')
	joint_positions.append(-1.5)
	# LH foot
	joint_names.append('lh_haa_joint')
	joint_positions.append(-0.2)
	joint_names.append('lh_hfe_joint')
	joint_positions.append(-0.75)
	joint_names.append('lh_kfe_joint')
	joint_positions.append(1.5)
	# RH foot
	joint_names.append('rh_haa_joint')
	joint_positions.append(-0.2)
	joint_names.append('rh_hfe_joint')
	joint_positions.append(-0.75)
	joint_names.append('rh_kfe_joint')
	joint_positions.append(1.5)

	joint_names.append('hokuyo_joint')
	joint_positions.append(0.0)


	gazebo_namespace = '/gazebo'
	rospy.wait_for_service('%s/set_model_configuration'%(gazebo_namespace))
	rospy.sleep(sleep_time)
	try:
		success = gazebo_interface.set_model_configuration_client(model_name, param_name, 
                                                                  joint_names, joint_positions, gazebo_namespace)
	except rospy.ServiceException, e:
		print "set model configuration service call failed: %s"%e

	rospy.wait_for_service('%s/unpause_physics'%(gazebo_namespace))
	try:
		success = unpause(gazebo_namespace)
	except rospy.ServiceException, e:
		print "unpause physics service call failed: %s"%e

	rospy.init_node('go0', anonymous=True)
	rospy.sleep(1)
